// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class Servis
{
        public const string leaderboard_total_wins = "CgkI8NeUtIUMEAIQCA"; // <GPGSID>
        public const string achievement_semipro = "CgkI8NeUtIUMEAIQAw"; // <GPGSID>
        public const string achievement_pro = "CgkI8NeUtIUMEAIQBA"; // <GPGSID>
        public const string leaderboard_win_streak = "CgkI8NeUtIUMEAIQBw"; // <GPGSID>
        public const string achievement_amateur = "CgkI8NeUtIUMEAIQAg"; // <GPGSID>
        public const string achievement_legend = "CgkI8NeUtIUMEAIQBQ"; // <GPGSID>
        public const string leaderboard_total_games_played = "CgkI8NeUtIUMEAIQBg"; // <GPGSID>
        public const string leaderboard_total_losses = "CgkI8NeUtIUMEAIQCg"; // <GPGSID>
        public const string leaderboard_lose_streak = "CgkI8NeUtIUMEAIQCQ"; // <GPGSID>
        public const string achievement_rookie = "CgkI8NeUtIUMEAIQAQ"; // <GPGSID>

}

